from __future__ import annotations

import csv
import json
from pathlib import Path

import numpy as np

from tunnel_analysis.io_layer import BaseLayer
from tunnel_analysis.timeseries import TimeSeriesLayer

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "data" / "curved_real_scale_railway_tunnel_t0t5"
REGULAR = BASE / "clean_lining_dataset" / "las_export"
RAYCAST = BASE / "field_like_raycast_dataset" / "clean_lining_dataset" / "las_export"
OUT = BASE / "raycast_vs_regular_comparison"
EPOCHS = ["T0", "T1", "T2", "T3", "T4", "T5"]
GT_MM = {"T0": 0.0, "T1": -10.0, "T2": -22.0, "T3": -38.0, "T4": -58.0, "T5": -80.0}


def load_epochs(folder: Path) -> list[np.ndarray]:
    loader = BaseLayer()
    return [loader.load_scan(str(folder / f"{epoch}.las")).points for epoch in EPOCHS]


def run_series(folder: Path) -> dict[str, object]:
    ts = TimeSeriesLayer()
    epochs = load_epochs(folder)
    return ts.spatiotemporal_series(
        epochs,
        labels=EPOCHS[1:],
        cyl_radius=0.5,
        normal_radius=0.6,
        max_corepoints=50_000,
    )


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    regular = run_series(REGULAR)
    raycast = run_series(RAYCAST)

    rows = []
    for i, epoch in enumerate(EPOCHS):
        if epoch == "T0":
            regular_p95 = raycast_p95 = regular_median = raycast_median = 0.0
            regular_inc = raycast_inc = 0.0
            method = str(raycast.get("method", regular.get("method", "unknown")))
        else:
            j = i - 1
            regular_p95 = float(np.asarray(regular["p95_abs_mm"])[j])
            raycast_p95 = float(np.asarray(raycast["p95_abs_mm"])[j])
            regular_median = float(np.asarray(regular["median_mm"])[j])
            raycast_median = float(np.asarray(raycast["median_mm"])[j])
            regular_inc = float(np.asarray(regular["incremental_p95_abs_mm"])[j])
            raycast_inc = float(np.asarray(raycast["incremental_p95_abs_mm"])[j])
            method = str(raycast.get("method", regular.get("method", "unknown")))
        gt_abs = abs(GT_MM[epoch])
        rows.append({
            "epoch": epoch,
            "ground_truth_abs_mm": round(gt_abs, 3),
            "tool_regular_p95_abs_mm": round(regular_p95, 3),
            "tool_raycast_p95_abs_mm": round(raycast_p95, 3),
            "regular_error_abs_mm": round(regular_p95 - gt_abs, 3),
            "raycast_error_abs_mm": round(raycast_p95 - gt_abs, 3),
            "raycast_minus_regular_mm": round(raycast_p95 - regular_p95, 3),
            "tool_regular_median_signed_mm": round(regular_median, 3),
            "tool_raycast_median_signed_mm": round(raycast_median, 3),
            "tool_regular_incremental_p95_mm": round(regular_inc, 3),
            "tool_raycast_incremental_p95_mm": round(raycast_inc, 3),
            "method": method,
        })

    csv_path = OUT / "tool_step6_comparison_metrics.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    summary = {
        "regular_las_dir": str(REGULAR),
        "raycast_las_dir": str(RAYCAST),
        "method": rows[-1]["method"],
        "metric": "Step 6 TimeSeriesLayer.spatiotemporal_series p95_abs_mm",
        "regular_mae_to_gt_abs_mm": round(float(np.mean([abs(r["regular_error_abs_mm"]) for r in rows])), 3),
        "raycast_mae_to_gt_abs_mm": round(float(np.mean([abs(r["raycast_error_abs_mm"]) for r in rows])), 3),
    }
    (OUT / "tool_step6_comparison_summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")

    lines = [
        "# Tool Step 6 Comparison",
        "",
        "This table is generated by the app core Step 6 time-series API, not by the external crown benchmark.",
        "",
        f"- Method: {summary['method']}",
        f"- Regular MAE to GT absolute settlement: {summary['regular_mae_to_gt_abs_mm']:.2f} mm",
        f"- Raycast MAE to GT absolute settlement: {summary['raycast_mae_to_gt_abs_mm']:.2f} mm",
        "",
        "| Epoch | GT abs mm | Tool regular p95 | Tool raycast p95 | Regular err | Raycast err | Raycast-Regular |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        lines.append(
            f"| {row['epoch']} | {row['ground_truth_abs_mm']:.1f} | {row['tool_regular_p95_abs_mm']:.1f} | "
            f"{row['tool_raycast_p95_abs_mm']:.1f} | {row['regular_error_abs_mm']:+.1f} | "
            f"{row['raycast_error_abs_mm']:+.1f} | {row['raycast_minus_regular_mm']:+.1f} |"
        )
    (OUT / "tool_step6_comparison_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(json.dumps(summary, indent=2))
    print(f"wrote: {csv_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
